# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jeremias Gätjens
email: 7gatjen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Junior freelance frontend developer based in the Costa Rica.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/Jere7/jeregatjens.github.io/" # the base hostname & protocol for your site
twitter_username: jeregatjens
github_username:  jeregatjens
linkedin_username:  jeregatjens

# Build settings
markdown: kramdown
